# Generated by Django 5.0.1 on 2024-05-18 22:28

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistIPAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('reason', models.TextField()),
                ('start_of_blocking', models.DateTimeField(auto_now_add=True)),
                ('end_of_blocking', models.DateTimeField(default=datetime.datetime(2054, 5, 11, 22, 28, 31, 350081, tzinfo=datetime.timezone.utc))),
            ],
            options={
                'verbose_name': 'Blacklist ip address',
                'verbose_name_plural': 'Blacklist ip addresses',
                'db_table': 'blacklist_ip_address',
            },
        ),
        migrations.CreateModel(
            name='BlacklistUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('start_of_blocking', models.DateTimeField(auto_now_add=True)),
                ('end_of_blocking', models.DateTimeField(default=datetime.datetime(2054, 5, 11, 22, 28, 31, 349102, tzinfo=datetime.timezone.utc))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blacklist user',
                'verbose_name_plural': 'Blacklist users',
                'db_table': 'blacklist_user',
            },
        ),
    ]
